### ISSUE TITLE
make this `pip install`-able 

### ISSUE THREAD

**Issue by volodymyrss** [oda-hub/renku-aqs#37]
add minimal generic python code here to enable jupyter extension

**Comment by burnout87** [comment]
Following the `vs-code` binder example, the `setup.py` now includes the `jupyter_serverproxy_servers` entry point, this enables the `Graph` button within jupyterlab.

https://github.com/oda-hub/renku-aqs/blob/cli-display-graph/setup.py

**Comment by volodymyrss** [comment]
need a small readme to be tested by @volodymyrss @ferrigno @andriineronov

**Comment by volodymyrss** [comment]
we might need to add it to repository template.
need an explanation how to show graph in https://renkulab.io/gitlab/astronomy/mmoda/oda-sdss

**Comment by burnout87** [comment]
While testing the installation of the plugin on the [repo](https://renkulab.io/gitlab/astronomy/mmoda/oda-sdss), I noticed that it was still based with an old version of renku.

Since the plugin now uses the latest renu version (`2.1.0`) I performed the migration (`renku migrate`), which completed successfully, and then I wanted to test the plugin, but it failed. So I tried also to run a more simple renku command (`renku workflow ls`), but it failed in a similar fashion. In particular, the error is the following:

`AttributeError: module 'renku.domain_model.project' has no attribute 'ProjectTemplateMetadata'`

Any ideas of what the issue could be @rokroskar ?

**Comment by rokroskar** [comment]
I think @Panaetius needs to help here... I'm not sure about the changes to the models in 2.x

**Comment by Panaetius** [comment]
you only get that error when accessing a project migrated to 2.x with a renku version < 2.x. Are you sure you're running the newest version of renku (check with `renku --version`)?

**Comment by burnout87** [comment]
> you only get that error when accessing a project migrated to 2.x with a renku version < 2.x. Are you sure you're running the newest version of renku (check with `renku --version`)?

Thanks @Panaetius , I did check the version and I though I was running the most recent (but apparently it was not the case). I upgraded and I now the error disappeared.

**Comment by Panaetius** [comment]
if you're in a session, maybe the Dockerfile still installs an old version so you get the old one every time you launch it?

**Comment by volodymyrss** [comment]
this is done, yes @burnout87 ?

**Comment by volodymyrss** [comment]
let's discuss if this is done today @burnout87

**Comment by burnout87** [comment]
since the plugin is also pushed to pypi, it is now complete
